### PR TITLE
support for scaffoldBB

### PR DESCRIPTION
**Pull request by MannixMD**

### CODE REVIEW

**Comment by MannixMD** [comment]
Thank you for suggestion. It all should be ok now. One thing tho for the future please don't use id for styling :)

**Comment by iMattPro** [comment]
That's much better. Are you working with the latest pull of this repo, because I did a quick test with your style and the new FONTS menu in ABBC3 really got broken by your style, because it's not a simple select menu anymore, it's now a dropdown toggle just like the Quick Links menu from the nav bar.

**Comment by MannixMD** [comment]
I need to stop spliting repos from the local environment silly me :(. Font dropdown should be fixed now :)

**Comment by MannixMD** [comment]
I've got a question for you about including other files. It has nothing to do with this extension but do you know if it's possible to include a html event file from all directory to another one? Basically i need to load the content from an event file from **all** directory into the same event file under "scaffoldBB" directory and then below add my modification is that possible? So it's like you mentioned earlier with css but for html

**Comment by iMattPro** [comment]
I don't think so. Have you tried it to see?

**Comment by MannixMD** [comment]
Yeah i did but no luck even with absolute path

**Comment by iMattPro** [comment]
I tried this out. The font menu dropdown was not working, giving an i.popper error in the console.

**Comment by MannixMD** [comment]
Weird, it works for me just fine no errors
(2) Board33 - Post a reply localhost b76989e76f01
(2) Board33 - Post a reply localhost ad2ca9974838
Maybe clear cache on your test board

**Comment by iMattPro** [comment]
> Weird, it works for me just fine no errors
> (2) Board33 - Post a reply localhost b76989e76f01
> (2) Board33 - Post a reply localhost ad2ca9974838
> Maybe clear cache on your test board

Still not working. Only works if I add popper to your style
```
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
```

**Comment by MannixMD** [comment]
I just grabbed the master branch and installed it on my board and it's working fine. You can check it [here](http://mannixstyles.byethost3.com/)

**Comment by MannixMD** [comment]
ok i found the issue. When Allow usage of third party content delivery networks is set to yes it's not working

**Comment by MannixMD** [comment]
Just send a new style revision for validation with the fix :)

**Pull request merged**
